server:
  port: 8080

spring:
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: shzh1997
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  security:
    jwt:
      secret: mySuperSecretKeyForJwtGeneration

