-- Таблица расходов
create table expenses (
    id          bigint generated by default as identity primary key,
    amount      numeric(18, 2) not null, -- 18,2 — обычно достаточно для денег
    category    varchar not null,
    date        timestamp(6) not null default current_timestamp,
    description varchar(255),
    user_id     bigint not null,
    constraint fk_expenses_user foreign key (user_id) references users(id) on delete cascade
);